[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0" # Ruff version
hooks = [
    # Run the linter.
    { id = "ruff-check", args = ["--fix"], types_or = ["python", "pyi"] },

    # Run the formatter.
    { id = "ruff-format", types_or = ["python", "pyi"] },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.8"                                      # uv version
hooks = [{ id = "uv-lock" }, { id = "uv-export" }]
